# Description: Dockerfile for server

FROM node:19-slim

RUN mkdir -p /opt/server

WORKDIR /opt/server

# copy project package files
COPY package.json .
COPY yarn.lock .

# install dependencies
RUN yarn install --production

# copy server files
COPY dist/apps/server .

# expose port 3000
EXPOSE 3000

# making sure container starts from the right folder
WORKDIR /opt/server

# run server
ENTRYPOINT ["node", "main.js"]


