version: "3.9"
name: sedma

services:
  server:
  # it restarts after every error and is created form the image stated below 
    restart: always
    image: tamarasov/sedma-server:latest
    environment:     
      - VIRTUAL_HOST=api.sedma.spv99.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api.sedma.spv99.com
      # top 3 are used by Hetzner service, the three below are mine. 
      - CLIENT_URL=https://sedma.spv99.com     
      - PORT=3000
      - DEBUG=${DEBUG}

    # states the the service will be connected to network proxy net - network of the provider - and accessible on port 3000
    networks:
      - proxy-net
    expose:
      - 3000
   

  client:
    restart: always
    image: tamarasov/sedma-client:latest
    # is run only after server
    depends_on:
      - server
    environment:
      - VIRTUAL_HOST=sedma.spv99.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=sedma.spv99.com
   
    expose:
      - 80
    networks:
      - proxy-net

# declares the existance of proxy net, stating it was created externally, so doen't need to be created.
networks:  
  proxy-net:
    name: proxy-net
    external: true