# Description: Dockerfile for server

FROM node:19-slim

RUN mkdir -p /server
WORKDIR /server

COPY package.json .
COPY package-lock.json .

# install dependencies
RUN npm install --production
# copy server files
COPY dist/apps/server .
EXPOSE 3000

WORKDIR /server

# run server
ENTRYPOINT ["node", "main.js"]


