name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push server
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sedma-server:latest
      -
        name: Build and push client
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sedma-client:latest          